# GoReleaser configuration for mdb
project_name: mdb

# Release configuration
release:
  github:
    owner: vb140772
    name: min-ops

# Generate changelog from git commits
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge branch
      - Merge pull request

# Build configuration
builds:
  - id: mdb
    binary: mdb
    main: .
    dir: .
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X 'main.Version={{.Version}}'
      - -X 'main.Commit={{.Commit}}'
      - -X 'main.BuildDate={{.Date}}'
    env:
      - CGO_ENABLED=0
    # Skip invalid targets (e.g., darwin/arm64 for older Go versions)
    skip: false

# Completion scripts
completions:
  - name: bash
    cmd: "mdb completion bash"
    shells: [bash]
    description: "Bash completion for mdb"
  - name: zsh
    cmd: "mdb completion zsh"
    shells: [zsh]
    description: "Zsh completion for mdb"

# Archive configuration
archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip
    # Only include files that exist (paths relative to workdir)
    files:
      - README.md
      - completions/**/*
    allow_different_binary_count: true

# Checksums
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

# Homebrew
brews:
  - name: mdb
    description: "MinIO Debug - analyze MinIO diagnostic JSON files"
    homepage: "https://github.com/vb140772/min-ops"
    license: "MIT"
    repository:
      owner: vb140772
      name: homebrew-mdb
    directory: Formula
    commit_author:
      name: "GitHub Actions"
      email: "actions@github.com"
    test: |
      system "#{bin}/mdb version"
    install: |
      bin.install "mdb"
      bash_completion.install "completions/bash/mdb" => "mdb"
      zsh_completion.install "completions/zsh/_mdb"

# Scoop (optional - uncomment if you want to publish to Scoop)
# scoops:
#   - name: mdb
#     bucket:
#       owner: vb140772
#       name: scoop-bucket
#     homepage: https://github.com/vb140772/min-ops
#     description: MinIO Debug - analyze MinIO diagnostic JSON files
#     license: MIT

# Snapcraft (optional - uncomment if you want to publish to Snap)
# snaps:
#   - name: mdb
#     publish: true
#     summary: MinIO Debug Tool
#     description: |
#       A command-line tool for analyzing MinIO cluster diagnostic JSON files.
#     grade: stable
#     confinement: strict
#     apps:
#       mdb:
#         command: mdb

# Docker (optional - uncomment if you want to create Docker images)
# dockers:
#   - goos: linux
#     goarch: amd64
#     image_templates:
#       - "vb140772/mdb:{{ .Version }}"
#       - "vb140772/mdb:latest"
#     dockerfile: Dockerfile

# Announcements (optional - uncomment to announce releases)
# announce:
#   twitter:
#     enabled: false
#   slack:
#     enabled: false

